#!/bin/bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

handle_existing_file() {
    FILE_PATH=$1

    if [ -L $FILE_PATH ]; then
	rm -rf $FILE_PATH
    fi
}

# Tmux
handle_existing_file "$HOME/.tmux.conf"
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# T
handle_existing_file "$HOME/.local/bin/t"
ln -s $DOTFILES/scripts/t "$HOME/.local/bin/t"

# Tmux
handle_existing_file "$HOME/.config/lvim"
ln -s $DOTFILES/lvim "$HOME/.config/lvim"

