#!/bin/bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

source "$DOTFILES/src/functions.sh"

install_packages
install_docker
install_astronvim
install_php
install_warpterminal
install_tmux
install_zapzsh

# Install zsh dotfile.
[ -f "$HOME/.zshrc" ] && mv "$HOME/.zshrc" "$HOME/.zshrc.bkp"
cp "$DOTFILES/zsh/zshrc" "$HOME/.zshrc"

