#!/bin/bash


# ----------------------------------------------------
# Set Colors
# ----------------------------------------------------
export red=$(tput setaf 1)
export green=$(tput setaf 2)
export yellow=$(tput setaf 3)
export blue=$(tput setaf 4)
export reset=$(tput sgr0)


# ----------------------------------------------------
# Functions
# ----------------------------------------------------
function error() {
    echo "[${red}-${reset}] $1"
}

function success() {
    echo "[${green}-${reset}] $1"
}

function info() {
    echo "[${blue}+${reset}] $1"
}

function warning() {
    echo "[${yellow}+${reset}] $1"
}

function display_banner() {
    printf "\n"
    echo "  / _ \/ __ \/_  __/ __/  _/ /  / __/ __/"
    echo " / // / /_/ / / / / _/_/ // /__/ _/_\ \_"
    echo "/____/\____/ /_/ /_/ /___/____/___/___(_)"
    printf "by daniel-felipe\n\n"
}

function arch() {
    info "Initalizing arch setup"
    source "setup/arch/setup.sh"
}

function ubuntu() {
    # TODO: Ubuntu setup
    warning "Not implemented yet."
}

function dotfiles() {
    info "Copying dotfiles"
    source "setup/dotfiles.sh"
}

function usage() {
    echo "Usage: $0 [-a] [-u] [-d]"
    echo "  -a        Initialize Arch based linux setup"
    echo "  -u        Initialize Ubuntu based linux setup"
    echo "  -d        Copy dotfiles only"
    exit 1
}

# ----------------------------------------------------
# Entry Point
# ----------------------------------------------------
DOTFILES=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
display_banner

[ "$#" -eq 0 ] && usage

while getopts ':aud' distro; do
    case "$distro" in
        a) arch ;;
        u) ubuntu ;;
        d) dotfiles ;;
        *) usage ;;
    esac
done
