# -------------------------------------------------------------
# Path
# -------------------------------------------------------------
export PATH="$PATH:/opt/nvim-linux64/bin"

# -------------------------------------------------------------
# Plugins
# -------------------------------------------------------------
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"
plug "zsh-users/zsh-autosuggestions"
plug "zap-zsh/supercharge"
plug "zap-zsh/zap-prompt"
plug "zsh-users/zsh-syntax-highlighting"
plug "agkozak/zsh-z"

# -------------------------------------------------------------
# Functions
# -------------------------------------------------------------
nah () {
    git reset --hard
    git clean -df
    if [ -d ".git/rebase-apply" ] || [ -d ".git/rebase-merge" ]; then
        git rebase --abort
    fi
}

# -------------------------------------------------------------
# Aliases
# -------------------------------------------------------------
alias ls='exa --icons'
alias ll='ls -lh'

# Laravel
alias sail='./vendor/bin/sail'
alias phpstan='./vendor/bin/phpstan'
alias vim='nvim'
alias ccache='composer install && composer dump-autoload && php artisan migrate:fresh --seed'

